name: Node.js CI

on:
  pull_request:
    branches: [master]
    paths:
      - 'backend/**'
  push:
    branches: [master]
    paths:
      - 'backend/**'

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1

      - name: Install dependecies
        working-directory: 'backend/'
        run: yarn install

      - name: Run Tests
        working-directory: 'backend/'
        run: yarn test

  Deploy:
    needs: Test
    defaults:
      run:
        working-directory: 'backend/'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'timexonesyncer'
          heroku_email: 'neupanebishal07@gmail.com'
