name: Node.js CI

on:
  pull_request:
    branches: [master]
    paths:
      - 'backend/**'

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1

      - name: Install dependecies
        working-directory: 'backend/'
        run: yarn install

      - name: Run Tests
        working-directory: 'backend/'
        run: yarn test
