name: Node.js Continuous Integeration

on:
  pull_request:
    branches: [master]
    paths:
      - 'backend/'

jobs:
  testPullRequest:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 'backend/'

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependecies
        run: yarn install

      - name: Run Tests
        run: yarn test
